"""Add attachments to conversation_messages

Revision ID: 940f8fd2c35e
Revises: aea8434b5651
Create Date: 2025-12-30 21:46:27.194706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940f8fd2c35e'
down_revision: Union[str, None] = 'aea8434b5651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admins_active'), table_name='admins')
    op.drop_index(op.f('idx_admins_email'), table_name='admins')
    op.add_column('conversation_messages', sa.Column('attachments', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_plan_configs_active'), table_name='subscription_plan_configs')
    op.drop_index(op.f('idx_plan_configs_name'), table_name='subscription_plan_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_plan_configs_name'), 'subscription_plan_configs', ['plan_name'], unique=False)
    op.create_index(op.f('idx_plan_configs_active'), 'subscription_plan_configs', ['is_active'], unique=False)
    op.drop_column('conversation_messages', 'attachments')
    op.create_index(op.f('idx_admins_email'), 'admins', ['email'], unique=False)
    op.create_index(op.f('idx_admins_active'), 'admins', ['is_active'], unique=False)
    # ### end Alembic commands ###
